name = "reddit-pain-finder"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "reddit-pain-finder"
database_id = "ed404205-31e1-4d19-ba4e-994a0e269112"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "ideas.koda-software.com/*"
zone_name = "koda-software.com"
